name: Deploy CSS to GitHub Pages

on:
    push:
        branches:
            - main # Trigger on push to 'main' branch

permissions:
    contents: write # Allow push access to the repository contents

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up git config
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"

            - name: Keep only CSS file at the root
              run: |
                  cp styles/ss-pdf.css .
                  cp styles/ts-pdf.css .
                  rm -rf .github/ styles/  # Remove other directories in the branch

            - name: Commit and push changes to 'gh-pages' branch
              run: |
                  git checkout -b gh-pages # Create the 'gh-pages' branch
                  git add .
                  git commit -m "Deploy CSS file to GitHub Pages" || echo "No changes to commit"
                  git push origin gh-pages --force
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
