name: Deploy CSS to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Git
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"

            - name: Copy CSS file to the correct folder
              run: |
                  mkdir -p docs
                  cp styles/ss-pdf.css docs/

            - name: Commit and push to gh-pages
              run: |
                  git checkout gh-pages || git checkout --orphan gh-pages
                  git reset --mixed
                  git rm -rf .
                  git clean -fdx
                  git restore --source=main -- docs/ss-pdf.css
                  git add docs/ss-pdf.css
                  git commit -m "Deploy CSS file to GitHub Pages" || echo "No changes to commit"
                  git push origin gh-pages --force
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
