name: Deploy CSS to GitHub Pages

on:
    push:
        branches:
            - main # Trigger on push to 'main' branch

permissions:
    contents: write # Allow push access to the repository contents

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2

            # Copy the CSS file to the folder where you want it to be served
            - name: Copy CSS file to the correct folder
              run: |
                  mkdir -p docs  # Create a 'docs' folder or use your preferred folder
                  cp styles/ss-pdf.css docs/

            # Commit and push changes to the 'gh-pages' branch
            - name: Clean working directory
              run: git clean -fdx # Remove untracked files and directories

            - name: Commit and push changes
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"
                  git checkout -b gh-pages || git checkout gh-pages  # Create or switch to the 'gh-pages' branch
                  git pull origin gh-pages --rebase  # Pull the latest changes from 'gh-pages' and rebase
                  git add docs/ss-pdf.css
                  git commit -m "Deploy CSS file to GitHub Pages" || echo "No changes to commit"
                  git push origin gh-pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
