name: Deploy CSS to GitHub Pages

on:
    push:
        branches:
            - main # Trigger on push to 'main' branch

permissions:
    contents: write # Allow push access to the repository contents

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2

            # Ensure the 'docs' directory exists and contains the desired CSS file
            - name: Prepare docs directory
              run: |
                  mkdir -p docs  # Create a 'docs' folder if it doesn't exist
                  cp styles/ss-pdf.css docs/  # Copy the CSS file to 'docs'

            # Switch to the gh-pages branch
            - name: Switch to gh-pages branch
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"
                  git checkout -b gh-pages || git checkout gh-pages  # Create or switch to the 'gh-pages' branch

            # Clean the branch and copy only the 'docs' directory to the root
            - name: Clean and add docs directory
              run: |
                  cp -r docs/* .  # Copy contents of 'docs' to the root
                  rm -rf .github/ styles/  # Remove all existing files in the branch
                  ls -la  # List files to verify

            # Commit and push changes to the gh-pages branch
            - name: Commit and push changes
              run: |
                  git add .
                  git commit -m "Deploy CSS file to GitHub Pages" || echo "No changes to commit"
                  git push origin gh-pages --force
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
